### ISSUE TITLE
nix-shell invocation from README fails

### ISSUE THREAD

**Issue by nh2** [tensorflow/haskell#141] opened 2017-07-03 21:38 UTC
```
$ nix-shell tools/userchroot.nix
error: attribute ‘dev’ missing, at /home/niklas/src/haskell/haskell-tensorflow/tools/userchroot.nix:37:9
(use ‘--show-trace’ to show detailed location information)
```

Which version/commit of nixpkgs is this expected to work on?

**Comment by nh2** [comment] 2017-07-03 21:38
(I'm on commit `4ab9cb9cf274e88eababfaba85103e3890a96afc` of `tensorflow/haskell`.)

**Comment by fkm3** [comment] 2017-07-03 21:50
@grwlf, do you know the answer?

**Comment by nh2** [comment] 2017-07-04 00:58
It looks like you're using something somewhere on nixpkgs master; I recommend for reproducibility that you provide a git commit of nixpkgs master, then one can invoke nix-shell specifically with that commit for total reproducibility.

**Comment by nh2** [comment] 2017-07-04 20:13
I managed to build it with

```
env NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs/archive/7d36ae33df.tar.gz nix-shell tools/userchroot.nix --pure
stack --stack-root $PWD/stack-root build --system-ghc
```

3 changes here to what's in the README:

* Gave explicit nixpkgs version (that one is one recent one from nixpkgs unstable, the 17.03 version didn't work)
* `--stack-root` to have it not use my user's `~/.stack` that may contain things I built before for other projects that don't work inside the nix environment, with errors like `/host/raid/stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2: error while loading shared libraries: libgmp.so.10: cannot open shared object file: No such file or directory`
* `--pure` so that external environment variables can't mess with it being reproducible

**Comment by blackgnezdo** [comment] 2017-07-04 20:46
@nh2 please turn this into a PR?

**Comment by nh2** [comment] 2017-07-04 20:50
@grwlf You added Nix support a short while ago, can you confirm if it builds fine with the nixpkgs commit that I use above?

**Comment by grwlf** [comment] 2017-07-10 13:02
Hi, Sorry for delay, I'll check the problem soon.

**Comment by grwlf** [comment] 2017-07-10 13:21
Yes, the problem was caused by incompatible **nixpkgs** tree. Thanks for the suggestions, they all make sense. I'll check nixpkgs version you have provided in a couple of days.

**Comment by nmattia** [comment] 2017-11-12 18:19
I think the `--stack-root` issue is better handled with an `export STACK_ROOT=$PWD/stack-root` shell hook in `tools/userchroot`. However I believe a simpler solution would be to use `stack --nix` instead, I've create #168 . `stack --nix foo` also makes sure that nix- and non-nix-built packages aren't mixed up.

**Comment by jyp** [comment] 2018-05-15 11:46
Is there a guide to build with nix? (I could build but the test suite fails, see https://github.com/tensorflow/haskell/issues/169)

@nmattia I see that your PR is still not merged after all this time. Is it obsolete?

**Comment by nmattia** [comment] 2018-05-15 12:35
It shouldn't be obsolete. I think we're waiting for a review from @grwlf .

**Comment by fkm3** [comment] 2018-08-03 02:13
The nix code has been updated quiet a bit, hopefully this is fixed now. Re-open if not.

**Closed by fkm3** 2018-08-03 02:13 UTC
